### PR TITLE
correct field name for workplace search github content source

### PR DESCRIPTION
**Pull request by gaoruifeng**
The field name for github content source should be `assigned_to`

### CODE REVIEW

**Comment by gtback** [comment]
Hi @gaoruifeng . Thanks for the update! 

These docs are generated from a private repository, so I'll let @chriscressman know, and he can update them there so these changes don't get accidentally overwritten later.

**Comment by chriscressman** [comment]
Thanks @gaoruifeng ! I opened a PR in the source repo. I'll comment again when the changes are live.

**Comment by chriscressman** [comment]
These changes are now live, back to 7.15. Thanks again!

**Comment by gaoruifeng** [comment]
Thanks, I am able to see the update now.

**Comment by gtback** [comment]
Thanks again @gaoruifeng !

**Pull request closed without merging**
